Repository rust-skia/rust-skia, pull requests merged in 2020-01, with the labels that each got.

#241 Add TextStyle::font_size
  skia-safe/src/modules/paragraph/text_style.rs
Labels: enhancement

#245 TypefaceFontProvider Into FontMgr
  skia-safe/src/modules/paragraph/typeface_font_provider.rs
Labels: api ergonomics

#251 Add -debug to the prebuilt libraries key so that we never mix up Skia…
  skia-bindings/build.rs
  skia-bindings/build_support/binaries.rs
  skia-bindings/build_support/skia.rs
Labels: bug, build

#255 Include skparagraph.patch in the crate to support fallback builds with "textlayout" enabled.
  skia-bindings/Cargo.toml
  skia-safe/Cargo.toml
Labels: bug, build

#260 README: Explain how the location of the LLVM installation is resolved on Windows
  README.md
Labels: enhancement

#259 Copy skia/LICENSE into the binary archives
  skia-bindings/build.rs
  skia-bindings/build_support/binaries.rs
Labels: build, enhancement

#263 Fix Azure CI Windows builds on image 20200102.1
  azure-pipelines-template.yml
Labels: build, regression

#264 Add CentOS 7 & 8 build instructions to the readme
  README.md
Labels: enhancement

#265 Dependency track env variable BUILD_ARTIFACTSTAGINGDIRECTORY
  skia-bindings/build_support/azure.rs
Labels: robustness

#269 [M80] Support to build Skia with CPU rendering only
  CMakeLists.txt
  azure-pipelines-template.yml
  skia-bindings/Cargo.toml
  skia-bindings/build_support/android.rs
  skia-bindings/build_support/ios.rs
  skia-bindings/build_support/skia.rs
  skia-bindings/src/bindings.cpp
  skia-bindings/src/bindings.h
  skia-bindings/src/gl.cpp
  skia-bindings/src/gpu.cpp
  skia-safe/Cargo.toml
  skia-safe/README.md
  skia-safe/examples/skia-org/drivers.rs
  skia-safe/examples/skia-org/drivers/gl.rs
  skia-safe/examples/skia-org/main.rs
  skia-safe/src/core/canvas.rs
  skia-safe/src/core/drawable.rs
  skia-safe/src/core/image.rs
  skia-safe/src/core/image_generator.rs
  skia-safe/src/core/surface.rs
  skia-safe/src/core/surface_characterization.rs
  skia-safe/src/gpu.rs
  skia-safe/src/gpu/backend_surface.rs
  skia-safe/src/gpu/context.rs
  skia-safe/src/lib.rs
Labels: enhancement

#275 Support Metal
  CONTRIBUTING.md
  Cargo.toml
  README.md
  azure-pipelines-build-target.yml
  skia-bindings/Cargo.toml
  skia-bindings/README.md
  skia-bindings/build_support.rs
  skia-bindings/build_support/ios.rs
  skia-bindings/build_support/skia.rs
  skia-bindings/build_support/xcode.rs
  skia-bindings/src/gpu.cpp
  skia-bindings/src/metal.cpp
  skia-org/Cargo.toml
  skia-org/src/artifact.rs
  skia-org/src/drivers.rs
  skia-org/src/drivers/cpu.rs
  skia-org/src/drivers/gl.rs
  skia-org/src/drivers/metal.rs
  skia-org/src/drivers/pdf.rs
  skia-org/src/drivers/svg.rs
  skia-org/src/drivers/vulkan.rs
  skia-org/src/main.rs
  skia-org/src/resources/color_wheel.png
  skia-org/src/resources/mandrill_512.png
  skia-org/src/skcanvas_overview.rs
  skia-org/src/skpaint_overview.rs
  skia-org/src/skparagraph_example.rs
  skia-org/src/skpath_overview.rs
  skia-org/src/skshaper_example.rs
  skia-safe/Cargo.toml
  skia-safe/README.md
  skia-safe/src/gpu.rs
  skia-safe/src/gpu/backend_surface.rs
  skia-safe/src/gpu/context.rs
  skia-safe/src/gpu/mtl.rs
  skia-safe/src/gpu/mtl/types.rs
Labels: enhancement
